@startuml


package "configs" {
    [BGL_WORK_CONFIG]
    [LIBERTY_WORK_CONFIG]
    [THUNDERBIRD_WORK_CONFIG]
    [TEST_WORK_CONFIG]
    [WORK_CONFIG_MAP]
[WORK_CONFIG_MAP] --> [BGL_WORK_CONFIG]
[WORK_CONFIG_MAP] --> [LIBERTY_WORK_CONFIG]
[WORK_CONFIG_MAP] --> [THUNDERBIRD_WORK_CONFIG]
[WORK_CONFIG_MAP] --> [TEST_WORK_CONFIG]
}


@enduml