@startuml
skinparam classAttributeIconSize 0
left to right direction
' top to bottom direction

skinparam linetype ortho
' skinparam linetype polyline

package "modules" {
    package "agents" {
        class SmartOperationAndMaintenanceAgent {
            + {static} TOP_K_ABNORMAL_LOGS: int
            + {static} LOG_EMBEDDING_BATCH_SIZE: int
            + lem: LogEmbedModel
            + adllm: AnomalyDetectionLLM
            + log_regex_replace_func: Callable[[str], str]
            + graph: CompiledStateGraph

            + {static} SmartOperationAndMaintenanceAgent(lem: LogEmbedModel, adllm: AnomalyDetectionLLM, log_regex_replace_func: Callable[[str], str]): Self
            + process_logs(logs: list[str]): str
            - _build_graph(): CompiledStateGraph
            
        }
    }

    package "models" {
        class LogEmbedModel {
            + {static} MAX_TOKEN_LEN: int
            + bert: BertModel
            + bert_tokenizer: BertTokenizerFast
            + device: torch.device

            + {static} new(bert_path: str, device: torch.device | str): Self
            + {static} from_pretrained(save_path: str, device: torch.device | str): Self
            - {static} _get_save_paths(save_path: str): LogEmbedModelSavePaths
            + pred(logs: list[str]): list[float]
            + forward(logs: list[str]): torch.Tensor
            + save_pretrained(save_path: str): None
        }

        class AnomalyDetectionLLM {
            + {static} MAX_TOKEN_LEN: int
            + llm: PeftModel
            + llm_tokenizer: AutoTokenizer
            + device: torch.device
            + max_logs_tokens_len: int
            + system_prefix_tokens: torch.Tensor
            + system_suffix_tokens: torch.Tensor
            + abnormal_output_tokens: torch.Tensor
            + normal_output_tokens: torch.Tensor

            + {static} new(base_llm_path: str, device: torch.device | str, system_name: str | None, field_names: str, torch_dtype: torch.dtype): Self
            + {static} from_pretrained(save_path: str, base_llm_path: str, device: torch.device | str, system_name: str | None, field_names: str, torch_dtype: torch.dtype): Self
            - {static} _get_save_paths(save_path: str): AnomalyDetectionLLMSavePaths
            + generate(log_win: list[str]): str
            + forward(log_win: list[list[str]], targets: list[int]): torch.Tensor
            + save_pretrained(save_path: str): None
            + set_system_name_and_field_names(system_name: str | None, field_names: str): None
            - _parse_log_win(log_win: list[str]): torch.Tensor
        }
    }

    package "configs" {
        stereotype WORK_CONFIG_MAP {
            ["BGL"]: BGL_WORK_CONFIG,
            ["Liberty"]: LIBERTY_WORK_CONFIG,
            ["Thunderbird"]: THUNDERBIRD_WORK_CONFIG,
            ["test"]: TEST_WORK_CONFIG,
        }
    }

    package "trainers" {
    }

    class train_adllm {}

    ' package "train_adllm" {
'         def train(
'     *,
'     adllm: models.AnomalyDetectionLLM,
'     epochs: int,
'     lr: float,
'     gradient_accumulation_steps: int,
'     train_loader: DataLoader, 
'     test_loader: DataLoader,
'     top_k_logs: int,
'     save_base: str,
' ) -> None:
    ' }
    package "train_lem" {}

    package "utils" {
        package "log_utils" {
            class LogDataFrameHelper {
                + {static} LogDataFrameHelper(): Self
                + save_to_csv(df: pd.DataFrame, path: str): None
                + build_struct_logs(log_path: str, log_format: str, start_line: int, end_line: int | None): pd.DataFrame
                + load_struct_logs(path: str): pd.DataFrame
                + build_semantic_logs(struct_logs_df: pd.DataFrame, feature_columns: list[str], log_regex_replace_func: Callable[[str], str]): pd.DataFrame
                + load_semantic_logs(path: str): pd.DataFrame
                + build_count_wins(df: pd.DataFrame, win_size_logs: int, win_step_logs: int): pd.DataFrame
                + build_time_wind(df: pd.DataFrame, win_size_secs: int, win_step_secs: int): pd.DataFrame
                + load_wins(path: str): pd.DataFrame
                + build_train_adllm_wins(win_df: pd.DataFrame, log_feature_vector_map: dict[str, float]): pd.DataFrame
                + load_train_adllm_wins(path: str): pd.DataFrame
            }
        }
    }
}

SmartOperationAndMaintenanceAgent --> LogEmbedModel
SmartOperationAndMaintenanceAgent --> AnomalyDetectionLLM
train_adllm ..> AnomalyDetectionLLM
train_lem ..> LogEmbedModel
@enduml